/**
 * Category page intro text — per nicchia/categoria
 * Testo pre-scritto (non serve Claude API, zero costo, istantaneo).
 * Sostituisce {{siteName}} al momento della generazione.
 * Target: 100-140 parole — abbastanza per evitare thin content, non troppo da oscurare gli articoli.
 */

const INTROS = {
  'home-improvement-costs': {
    'hvac': {
      headline: 'HVAC & Heating Cost Guides',
      intro: `Heating and cooling account for nearly half of most homes' energy bills — making HVAC one of the biggest home improvement investments you'll face. At {{siteName}}, our HVAC cost guides are researched with input from licensed contractors across the US to give you realistic, region-specific price ranges. Whether you're replacing a central air system, installing a heat pump, or just comparing furnace brands, you'll find straightforward breakdowns of what labor, equipment, and permits actually cost — with no fluff or sales pressure.`,
    },
    'bathroom': {
      headline: 'Bathroom Remodel Cost Guides',
      intro: `A bathroom remodel can range from a $3,000 cosmetic refresh to a $30,000+ full gut renovation — and knowing which factors drive that difference is the key to budgeting correctly. {{siteName}}'s bathroom cost guides break down prices by scope, fixture quality, and region, drawing on contractor data and real homeowner project costs. From walk-in shower conversions to full primary bath renovations, our guides help you set realistic expectations before you call a single contractor.`,
    },
    'kitchen': {
      headline: 'Kitchen Remodel Cost Guides',
      intro: `The kitchen is the most expensive room to remodel — and the one with the highest return on investment. {{siteName}} covers the full cost spectrum of kitchen renovations, from cabinet refacing and countertop replacements to complete layout changes with new plumbing and electrical. Our guides include real cost data by project size and material grade, so you can see what a mid-range kitchen upgrade actually costs versus a high-end renovation before committing to a budget.`,
    },
    'flooring': {
      headline: 'Flooring Installation Cost Guides',
      intro: `Flooring costs vary dramatically by material — from $2/sq ft for basic vinyl plank to $20+/sq ft for premium hardwood or tile. {{siteName}}'s flooring guides help you compare installation costs across every major material: hardwood, LVP, laminate, tile, carpet, and more. Each guide includes labor rates by region, subfloor prep costs, and the hidden expenses most contractors don't quote upfront, so your final bill doesn't come as a surprise.`,
    },
    'deck-patio': {
      headline: 'Deck & Patio Build Cost Guides',
      intro: `A well-built deck or patio adds real living space and strong resale value — but costs can swing wildly based on size, materials, and local permit requirements. {{siteName}}'s deck and patio cost guides cover composite vs. pressure-treated lumber, concrete vs. paver patios, pergola additions, and the permit costs you'll face by region. Whether you're budgeting a basic ground-level deck or a multi-level outdoor living area, our guides give you the numbers contractors expect to charge.`,
    },
    'roofing': {
      headline: 'Roof Replacement Cost Guides',
      intro: `Roof replacement is one of the largest and most urgent home expenses a homeowner faces. Costs depend on your roof size, pitch, material choice, and local labor rates — and quotes from different contractors can vary by thousands of dollars. {{siteName}}'s roofing cost guides break down per-square pricing for asphalt shingles, metal roofing, tile, and flat roofs, plus what to expect for tear-off, decking repairs, and permits, so you can evaluate contractor quotes with confidence.`,
    },
    'windows-doors': {
      headline: 'Window & Door Replacement Cost Guides',
      intro: `New windows and doors improve energy efficiency, security, and curb appeal — but installation costs vary significantly by window type, frame material, and the complexity of the opening. {{siteName}}'s window and door cost guides cover replacement windows, new construction installs, sliding glass doors, entry doors, and garage doors. Each guide includes per-unit labor and material costs, energy efficiency ROI data, and what to watch for when comparing contractor quotes.`,
    },
    'painting': {
      headline: 'Interior & Exterior Painting Cost Guides',
      intro: `Professional painting is one of the fastest ways to transform a home — and one of the most price-variable services contractors offer. Labor rates, paint quality, surface prep, and room count all affect your final bill significantly. {{siteName}}'s painting cost guides cover interior room painting, full house exterior projects, cabinet painting, and specialty finishes. We break down what painters charge per square foot, per room, and per project type so you can budget accurately and spot inflated quotes.`,
    },
    'plumbing': {
      headline: 'Plumbing Cost Guides',
      intro: `Plumbing repairs and replacements carry some of the widest cost ranges of any home service — a minor fix can cost $150 while a full repipe can exceed $15,000. {{siteName}}'s plumbing cost guides cover water heater replacement, pipe repair, drain cleaning, fixture installation, and whole-home repiping. Our guides include flat-rate vs. hourly pricing comparisons, emergency vs. scheduled service cost differences, and the red flags that signal a contractor is overcharging.`,
    },
    'electrical': {
      headline: 'Electrical Work Cost Guides',
      intro: `Electrical work is non-negotiable territory for licensed professionals — and costs reflect both the skill required and the safety liability involved. {{siteName}}'s electrical cost guides cover panel upgrades, EV charger installation, outlet and wiring work, whole-home rewiring, and generator hookups. We include permit costs, typical hourly rates by region, and the questions you should always ask an electrician before signing any estimate.`,
    },
  },

  'pet-care-by-breed': {
    'dogs': {
      headline: 'Dog Care Guides by Breed',
      intro: `Every dog breed comes with its own set of care needs, health risks, and lifetime costs — and understanding those specifics before you bring a dog home can save you thousands in unexpected vet bills. {{siteName}}'s dog breed guides cover grooming requirements, exercise needs, common health conditions, and annual ownership costs for the most popular breeds. Whether you're choosing between a Labrador and a Golden Retriever or trying to understand what owning a French Bulldog really costs, our guides give you the full picture.`,
    },
    'cats': {
      headline: 'Cat Care Guides by Breed',
      intro: `Cats are often described as low-maintenance pets, but breed matters more than most people realize. A Persian's grooming needs and a Maine Coon's medical costs are very different from those of a domestic shorthair. {{siteName}}'s cat breed guides break down care requirements, personality traits, common health problems, and annual ownership costs so you can find a cat that matches your lifestyle and budget — and care for them properly once they're home.`,
    },
    'birds': {
      headline: 'Bird Care Guides',
      intro: `Birds are intelligent, social, and often surprisingly long-lived — a parrot can be a 50-year commitment. {{siteName}}'s bird care guides cover diet, cage requirements, socialization needs, vet costs, and the species-specific challenges of the most popular pet birds. Whether you're considering a parakeet, a cockatiel, or an African Grey parrot, our guides help you understand exactly what responsible bird ownership involves before you make a decades-long commitment.`,
    },
    'small-pets': {
      headline: 'Small Pet Care Guides',
      intro: `Rabbits, hamsters, guinea pigs, and ferrets might be small, but their care needs are more complex than most people expect. {{siteName}}'s small pet guides cover habitat setup, diet, handling, common health issues, and the real annual costs of caring for each species. If you're choosing a first pet for a child or adding a small animal to your home, our guides will help you set up the right environment and avoid the most common care mistakes.`,
    },
    'fish': {
      headline: 'Fish & Aquarium Care Guides',
      intro: `Fishkeeping looks simple from the outside, but water chemistry, tank cycling, and species compatibility make it a surprisingly technical hobby. {{siteName}}'s fish and aquarium guides cover setup costs, filtration, stocking, feeding, and the most common reasons fish die in new tanks. From beginner-friendly betta bowls to fully planted community tanks, our guides help you avoid the expensive trial-and-error phase that catches most new fishkeepers off guard.`,
    },
  },

  'software-error-fixes': {
    'windows': {
      headline: 'Windows Error Fix Guides',
      intro: `Windows errors range from minor annoyances to system-stopping failures — and knowing which fixes actually work versus which waste your time is the difference between a 10-minute resolution and a full reinstall. {{siteName}}'s Windows error guides cover the most common crash codes, update failures, driver conflicts, and performance issues affecting Windows 10 and Windows 11. Each guide is written by a certified systems engineer with step-by-step instructions in plain English, tested on real hardware before publication.`,
    },
    'mac': {
      headline: 'Mac & iOS Error Fix Guides',
      intro: `Apple's ecosystem is known for reliability, but macOS and iOS errors still occur — and when they do, Apple's support documentation can be frustratingly vague. {{siteName}}'s Mac and iOS troubleshooting guides cover startup issues, app crashes, update failures, connectivity problems, and the common errors that follow major macOS version upgrades. Our step-by-step fixes are written for real users, not IT professionals, with clear instructions that don't require Terminal expertise.`,
    },
    'browsers': {
      headline: 'Web Browser Error Fix Guides',
      intro: `Browser errors — from ERR_CONNECTION_REFUSED to video playback failures — affect productivity more than almost any other software issue. {{siteName}}'s browser troubleshooting guides cover Chrome, Firefox, Safari, and Edge, addressing the most common errors users search for every day. Whether it's a stubborn extension conflict, a certificate error, or a browser that simply won't load pages, our guides provide the fastest verified path to a working browser.`,
    },
    'office': {
      headline: 'Microsoft Office Error Fix Guides',
      intro: `Office errors at the wrong moment can derail deadlines and cost hours of work. {{siteName}}'s Microsoft Office troubleshooting guides address the most disruptive errors in Word, Excel, Outlook, and PowerPoint — including file corruption, activation failures, crashing on open, and sync issues with OneDrive. Our fixes are tested on both Microsoft 365 subscription versions and standalone Office installations, with solutions for home users and enterprise environments.`,
    },
    'android': {
      headline: 'Android Error Fix Guides',
      intro: `Android's open ecosystem means more flexibility — and more ways for things to go wrong. {{siteName}}'s Android troubleshooting guides cover the most common issues across Samsung Galaxy, Google Pixel, and other Android devices: apps crashing, system freezes, connectivity failures, battery drain, and update problems. Each guide includes fixes that work without root access, along with escalation steps for issues that require a factory reset or manufacturer support.`,
    },
    'gaming': {
      headline: 'Gaming Error Fix Guides',
      intro: `Gaming errors — from Steam connection failures to game crashes mid-session — are some of the most frustrating tech problems users face. {{siteName}}'s gaming troubleshooting guides cover Steam, Xbox, PlayStation, and common PC gaming errors with fixes that are fast and actually verified to work. Whether it's a DirectX error, a driver conflict causing crashes, or an online connection issue blocking you from a multiplayer session, our guides get you back in the game with minimal downtime.`,
    },
  },

  'diet-specific-recipes': {
    'keto': {
      headline: 'Keto Recipes & Diet Guides',
      intro: `The ketogenic diet eliminates nearly all carbohydrates to push the body into a fat-burning metabolic state — but making it sustainable requires more than just avoiding bread. {{siteName}}'s keto recipe collection focuses on practical, genuinely satisfying meals that keep net carbs under 20g without making you feel like you're constantly missing out. Each recipe includes a full macro breakdown, prep time, and substitution options, developed by our nutrition specialist with years of experience helping clients stick with keto long-term.`,
    },
    'vegan': {
      headline: 'Vegan & Plant-Based Recipes',
      intro: `A well-planned vegan diet is one of the most nutritionally complete eating patterns available — but "well-planned" is the key phrase. {{siteName}}'s vegan recipe guides focus on meals that are protein-adequate, genuinely satisfying, and practical for everyday cooking — not just salads and smoothie bowls. Every recipe includes full nutritional information, notes on key nutrients to watch (B12, iron, omega-3s), and realistic prep times for weeknight cooking.`,
    },
    'gluten-free': {
      headline: 'Gluten-Free Recipes & Guides',
      intro: `Cooking gluten-free successfully goes beyond swapping regular flour for a GF alternative — cross-contamination risks, hidden gluten in processed foods, and the baking science behind wheat-free recipes all require specific knowledge. {{siteName}}'s gluten-free recipe guides are developed for people with celiac disease and gluten sensitivity alike, with clear labeling for certified GF ingredients and step-by-step techniques that produce results as good as their wheat-based counterparts.`,
    },
    'paleo': {
      headline: 'Paleo Recipes & Diet Guides',
      intro: `The paleo diet eliminates grains, legumes, dairy, and processed foods in favor of the whole foods humans evolved eating — but translating that principle into practical, enjoyable everyday meals takes creativity. {{siteName}}'s paleo recipe collection includes quick weeknight dinners, meal-prep friendly lunches, and weekend cooking projects that don't compromise on flavor. Each recipe is verified against strict paleo guidelines, with notes on common ingredients people mistakenly assume are paleo-compliant.`,
    },
    'mediterranean': {
      headline: 'Mediterranean Diet Recipes',
      intro: `The Mediterranean diet consistently ranks as the world's healthiest eating pattern — and unlike most "diets," it's built around abundance rather than restriction. Olive oil, fish, legumes, vegetables, whole grains, and moderate amounts of wine form the foundation. {{siteName}}'s Mediterranean recipe guides translate this research-backed eating style into approachable everyday meals, with a focus on the flavors of Southern Europe and the practical reality of cooking for a North American household.`,
    },
    'low-carb': {
      headline: 'Low-Carb Recipes & Guides',
      intro: `Low-carb eating doesn't mean zero-carb — and finding that sustainable middle ground between standard and ketogenic eating is where most people get the best long-term results. {{siteName}}'s low-carb recipe guides target 50-100g of net carbs per day, a level that supports weight management and blood sugar control without the strict tracking that keto requires. Recipes focus on real food, realistic prep times, and meals the whole family can eat — not just the person watching their carbs.`,
    },
    'intermittent-fasting': {
      headline: 'Intermittent Fasting Guides & Recipes',
      intro: `Intermittent fasting is less about what you eat and more about when — but what you eat during your eating window makes or breaks your results. {{siteName}}'s intermittent fasting guides cover the most popular protocols (16:8, 5:2, OMAD) with practical advice on breaking fasts without spiking insulin, managing hunger during fasting windows, and building eating-window meals that actually keep you full. We also address the specific nutritional considerations for women, athletes, and people over 50.`,
    },
  },

  'small-town-tourism': {
    'weekend-trips': {
      headline: 'Weekend Trip Guides',
      intro: `The best weekend trips aren't the ones you see on every travel blog — they're the ones that feel like genuine discoveries. {{siteName}}'s weekend trip guides cover small towns and destinations that reward the traveler willing to venture past the obvious tourist trails. Each guide includes where to stay, what to eat, the specific things worth your time, and a realistic budget breakdown, so you can plan a memorable two-day escape without the guesswork or the inflated travel magazine prices.`,
    },
    'hidden-gems': {
      headline: 'Hidden Gem Destination Guides',
      intro: `Hidden gems get discovered — that's the nature of travel. But the towns on {{siteName}}'s hidden gems list still have that quality that makes travel feel special: the sense that you've found something before the crowds. Our guides focus on destinations that haven't yet been overrun, the local businesses worth supporting, and the experiences you simply can't have in a major city. We update these guides regularly to reflect which towns are changing and which still feel genuinely off the beaten path.`,
    },
    'food-drink': {
      headline: 'Food & Drink Guides for Small Towns',
      intro: `Small towns punch well above their weight when it comes to food — farm-to-table before it was fashionable, local breweries built by people who actually live there, diners that have been serving the same perfect pie for 40 years. {{siteName}}'s food and drink guides focus on the restaurants, breweries, wineries, and coffee shops in small towns that are worth making a detour for. We skip the chain restaurants and the tourist traps, focusing only on places with genuine local character.`,
    },
    'outdoor': {
      headline: 'Outdoor & Nature Guides',
      intro: `Small towns are often the best base camps for outdoor adventures — closer to the trailhead, cheaper to stay, and free from the congestion that plagues popular national park gateway towns. {{siteName}}'s outdoor guides cover hiking, kayaking, cycling, and nature exploration accessible from small-town starting points, with practical details on trail difficulty, gear requirements, seasonal conditions, and the local outfitters worth using. Whether you're a serious hiker or just looking for a scenic morning walk, our guides help you find the right outdoor experience.`,
    },
    'history': {
      headline: 'History & Culture Guides',
      intro: `America's small towns are living history — from Civil War battlefields and gold rush remnants to immigrant communities that shaped entire industries. {{siteName}}'s history and culture guides go beyond the roadside historical marker to explore the stories, museums, and preserved places that make a town's past genuinely interesting. Each guide is researched with local historical societies and longtime residents to capture context and detail that Wikipedia entries simply don't have.`,
    },
    'accommodation': {
      headline: 'Where to Stay — Small Town Accommodation Guides',
      intro: `Where you stay shapes the entire experience of a small-town trip. The right inn, B&B, or vacation rental puts you in the middle of town within walking distance of everything — the wrong choice leaves you isolated in a highway motel. {{siteName}}'s accommodation guides for small towns focus on lodging options with genuine character: historic inns, owner-operated B&Bs, well-located vacation rentals, and the occasional boutique hotel that gets the atmosphere exactly right. We include honest price ranges and what to expect at each type of property.`,
    },
  },

  'personal-finance': {
    'budgeting': { headline: 'Budgeting Guides & Templates', intro: `A budget isn't a restriction — it's a roadmap. {{siteName}}'s budgeting guides cover every major approach, from zero-based budgeting and the 50/30/20 rule to envelope systems and app-based tracking. Whether you've never budgeted before or you've tried and given up, our step-by-step guides give you a realistic starting point based on your actual income and expenses — not a generic template that ignores rent prices and student loans.` },
    'saving': { headline: 'Saving Money Guides', intro: `Building savings requires strategy, not just willpower. {{siteName}}'s saving guides cover high-yield savings accounts, emergency fund targets by income, automated savings systems, and the specific moves that make the biggest difference fastest. We compare the best HYSA rates currently available, explain FDIC coverage limits, and give you a practical sequence for building your financial cushion — starting from zero or rebuilding after a setback.` },
    'investing': { headline: 'Investing for Beginners & Beyond', intro: `Investing is not complicated — but it's easy to make it complicated. {{siteName}}'s investing guides start with index funds and IRAs and build up to portfolio construction, tax-advantaged accounts, and common mistakes that cost investors thousands. Every guide is written for people who want to understand what they're doing, not just follow instructions blindly, with clear explanations of fees, risk, and the math behind long-term compounding.` },
    'debt-payoff': { headline: 'Debt Payoff Strategies', intro: `Debt payoff is math plus psychology — and {{siteName}} covers both. Our debt guides compare the avalanche and snowball methods with real numbers, walk through how to negotiate interest rates, and address the specific challenges of credit card debt, student loans, and medical bills. We also cover when consolidation or refinancing makes sense and when it doesn't, so you can make a decision based on actual cost rather than marketing promises.` },
    'retirement': { headline: 'Retirement Planning Guides', intro: `Retirement planning feels abstract until it suddenly feels urgent. {{siteName}}'s retirement guides help you understand the Roth vs. traditional IRA decision, 401(k) contribution limits and employer match mechanics, Social Security timing strategy, and how much you actually need to retire at different ages. Whether you're starting at 25 or catching up at 50, our guides give you a realistic, actionable path based on where you actually are.` },
    'side-income': { headline: 'Side Income & Side Hustles', intro: `A side income can change your financial trajectory faster than almost any other move — if you choose the right one for your skills and time. {{siteName}}'s side income guides cover the highest-earning opportunities realistically, including freelancing, service businesses, digital products, and passive income streams that actually generate meaningful money. We include startup costs, realistic earning potential, and the time commitment required so you can compare options honestly.` },
  },
  'insurance-guide': {
    'car-insurance': { headline: 'Car Insurance Cost & Coverage Guides', intro: `Car insurance rates vary by hundreds of dollars per year for the same driver and vehicle — and most people never shop around. {{siteName}}'s car insurance guides explain how rates are calculated, what coverage levels you actually need, and which discounts most drivers qualify for but don't claim. We break down liability, comprehensive, collision, and gap coverage in plain English, so you can make coverage decisions based on real protection rather than defaulting to the lowest premium.` },
    'health-insurance': { headline: 'Health Insurance Guides', intro: `Choosing a health insurance plan means comparing deductibles, premiums, networks, and out-of-pocket maximums — a combination most people find genuinely confusing. {{siteName}}'s health insurance guides explain every component of a plan in plain English, walk through the open enrollment process, and help you calculate your likely total annual cost under different scenarios. We cover marketplace plans, employer plans, COBRA, and short-term coverage for people navigating transitions.` },
    'life-insurance': { headline: 'Life Insurance Guides', intro: `Life insurance is straightforward once you understand the basics — but the industry's complexity and sales incentives make it easy to buy the wrong policy. {{siteName}}'s life insurance guides cut through the noise on term versus whole life, how much coverage you actually need, how to compare quotes across companies, and why most financial advisors recommend term for the majority of people. We include the questions you need to ask before signing anything.` },
    'home-insurance': { headline: 'Home Insurance Guides', intro: `Home insurance protects your largest asset — and most homeowners don't fully understand what their policy covers until they file a claim. {{siteName}}'s home insurance guides explain dwelling coverage, personal property limits, liability protection, and the specific exclusions that catch homeowners off guard (floods, earthquakes, sewer backup). We also cover how to compare quotes, when to raise your deductible, and what happens to your rate after a claim.` },
    'renters-insurance': { headline: 'Renters Insurance Guides', intro: `Renters insurance is one of the best deals in personal finance — $15-20 per month for coverage that protects everything you own. {{siteName}}'s renters insurance guides explain what's covered (and what's not), how to document your belongings correctly for a claim, and why liability coverage matters as much as the personal property protection. We compare the best renters insurance companies by price and claims satisfaction so you can get covered quickly.` },
    'other-insurance': { headline: 'Specialty Insurance Guides', intro: `Beyond the basics, a range of insurance products protects against specific, high-cost risks — travel delays, pet emergencies, disability, and excess liability. {{siteName}}'s specialty insurance guides help you evaluate whether each type of coverage is worth the premium based on your actual risk profile. We cover travel insurance, pet insurance, disability coverage, and personal umbrella policies with honest assessments of who needs them and who's wasting money on them.` },
  },
  'legal-advice': {
    'wills-trusts': { headline: 'Wills, Trusts & Estate Planning Guides', intro: `Estate planning isn't just for the wealthy — anyone with assets, dependents, or specific wishes about end-of-life care needs at least a basic will. {{siteName}}'s wills and trusts guides explain the difference between a will and a living trust, when a trust actually makes sense, how to designate beneficiaries correctly, and the common mistakes that send estates through expensive, delayed probate. We cover DIY options, online services, and when you genuinely need an estate attorney.` },
    'landlord-tenant': { headline: 'Landlord & Tenant Rights Guides', intro: `Landlord-tenant law varies significantly by state, and knowing your rights — whether you rent or own — can save you thousands. {{siteName}}'s landlord-tenant guides cover security deposit rules, lease terms, habitability standards, eviction procedures, and what to do when a dispute escalates. We explain the law in practical terms, with guidance on documentation, communication, and when the situation calls for legal help versus a strongly worded letter.` },
    'employment-law': { headline: 'Employment Law Guides', intro: `Most workers have more legal protections than they realize — and most employees who've been treated illegally never take action because they don't know their rights. {{siteName}}'s employment law guides cover wrongful termination, workplace discrimination, wage theft, non-compete agreements, and what to do if you believe your rights have been violated. We explain the difference between what's unfair and what's illegal, and when a consultation with an employment attorney changes everything.` },
    'family-law': { headline: 'Family Law Guides', intro: `Family law matters — divorce, custody, child support — are among the most emotionally and financially consequential legal situations most people face. {{siteName}}'s family law guides explain how courts approach custody determinations, how child support is calculated, what to expect from the divorce process, and how to protect your interests without escalating conflict unnecessarily. We cover both contested and uncontested processes and explain when mediation is genuinely more effective than litigation.` },
    'small-claims': { headline: 'Small Claims Court Guides', intro: `Small claims court is designed for people without lawyers — and for disputes under a few thousand dollars, it's often the most effective remedy available. {{siteName}}'s small claims guides walk through the process from filing to judgment: what documentation you need, how to present your case clearly, what defenses you're likely to face, and how to collect once you've won. We cover the limits and procedures for all 50 states, with state-specific detail on filing fees and dollar limits.` },
    'contracts': { headline: 'Contract & Legal Document Guides', intro: `Contracts govern everything from employment to apartment leases to freelance work — and most people sign them without fully understanding what they're agreeing to. {{siteName}}'s contract guides explain the most common terms and clauses in plain English, identify the provisions that actually matter versus standard boilerplate, and help you understand what you can negotiate versus what's typically non-negotiable. We also cover NDAs, non-competes, and what makes a contract legally enforceable.` },
  },
  'real-estate-investing': {
    'rental-property': { headline: 'Rental Property Investment Guides', intro: `Rental property can build substantial wealth — but only if the numbers actually work. {{siteName}}'s rental property guides cover how to analyze a deal, calculate cash flow and cap rate, screen tenants, manage maintenance costs, and understand the tax advantages of owning income property. We include realistic vacancy rates, repair reserves, and property management costs that beginning investors often leave out of their projections, giving you an accurate picture of actual returns.` },
    'house-hacking': { headline: 'House Hacking Guides', intro: `House hacking — buying a multifamily property or renting out part of your home — is one of the most powerful wealth-building strategies available to people without large capital reserves. {{siteName}}'s house hacking guides cover the FHA loan strategy, ADU conversion, duplex and triplex analysis, and how to structure your living situation to have tenants cover most or all of your housing costs. We include the tax implications, management realities, and specific scenarios that make house hacking work or fail.` },
    'reits': { headline: 'REIT Investment Guides', intro: `Real estate investment trusts let you invest in real estate without buying property — but not all REITs are created equal. {{siteName}}'s REIT guides explain the difference between equity, mortgage, and hybrid REITs, how to evaluate dividend yield and payout sustainability, the tax treatment of REIT distributions, and which REIT sectors have historically performed best across market cycles. We cover both publicly traded REITs and non-traded options with an honest assessment of liquidity and risk.` },
    'flipping': { headline: 'Fix & Flip Real Estate Guides', intro: `House flipping looks easy on television and is significantly harder in reality. {{siteName}}'s fix and flip guides cover how to find distressed properties, accurately estimate renovation costs before buying, calculate your maximum allowable offer, finance a flip without conventional bank loans, and manage a renovation project to protect your profit margin. We address the most common mistakes that kill flip profits — underestimating renovation costs, overestimating ARV, and holding properties too long.` },
    'financing': { headline: 'Real Estate Financing Guides', intro: `Financing determines your returns as much as the property itself — and the options for investment real estate go well beyond a conventional mortgage. {{siteName}}'s real estate financing guides cover conventional loans, DSCR loans, hard money, seller financing, HELOCs, and the specific requirements for investment property versus owner-occupied financing. We explain down payment requirements, rate differences, how lenders evaluate rental income, and which financing structure works best for different strategies.` },
    'market-analysis': { headline: 'Real Estate Market Analysis Guides', intro: `Buying in the right market matters as much as buying the right property. {{siteName}}'s market analysis guides teach you how to evaluate local markets for rental demand, appreciation potential, landlord-friendly laws, and population growth trends. We cover key metrics — cap rates, price-to-rent ratios, vacancy rates — and show you where to find reliable local data so you can make evidence-based decisions about where to invest rather than following media narratives about hot or cold markets.` },
  },
  'health-symptoms': {
    'heart-health': { headline: 'Heart Health Symptom Guides', intro: `Heart symptoms are among the most important to understand and the most frequently misattributed. {{siteName}}'s heart health guides explain what chest pain, palpitations, shortness of breath, and fatigue actually indicate — when they're benign and when they require immediate medical attention. Every guide is written with input from cardiologists and cross-referenced against current clinical guidelines, giving you the information you need to have an informed conversation with your doctor rather than dismissing symptoms or catastrophizing unnecessarily.` },
    'digestive': { headline: 'Digestive Health Symptom Guides', intro: `Digestive symptoms — bloating, acid reflux, irregular bowel habits — affect more than 70 million Americans and are among the most underdiagnosed health issues. {{siteName}}'s digestive health guides explain the difference between common functional issues like IBS and structural conditions that require investigation, what specific symptom patterns suggest to gastroenterologists, and what lifestyle and dietary changes have the strongest evidence behind them. Our guides help you identify what's worth reporting to a doctor and what responds well to self-care.` },
    'hormonal': { headline: 'Hormonal Health Guides', intro: `Hormonal imbalances affect energy, weight, mood, and reproductive health — but symptoms are often dismissed or misattributed for years before diagnosis. {{siteName}}'s hormonal health guides cover thyroid disorders, PCOS, perimenopause, low testosterone, and adrenal issues with detailed symptom breakdowns, diagnostic tests to ask for, and treatment options including both conventional and evidence-based integrative approaches. We help you build the vocabulary and knowledge to advocate effectively for appropriate testing.` },
    'pain-symptoms': { headline: 'Pain & Fatigue Symptom Guides', intro: `Chronic pain and persistent fatigue are among the most complex and frequently mismanaged symptoms in medicine. {{siteName}}'s pain and fatigue guides explain the most common underlying causes, red flags that warrant urgent evaluation, and the evidence behind different treatment approaches — from medication to physical therapy to lifestyle interventions. We specifically address the symptoms most commonly dismissed or underdiagnosed in women, including fibromyalgia, chronic fatigue syndrome, and autoimmune-related pain.` },
    'mental-symptoms': { headline: 'Mental Health Symptom Guides', intro: `Mental health symptoms have physical manifestations — and physical health problems have mental health consequences. {{siteName}}'s mental health symptom guides help you understand the difference between clinical anxiety and normal stress, depression and grief, and when symptoms are severe enough to warrant professional evaluation. We cover the overlap between mental and physical symptoms, what to expect from different types of treatment, and how to access care when cost or availability are barriers.` },
    'sleep': { headline: 'Sleep Problem & Insomnia Guides', intro: `Poor sleep affects every system in the body, but the causes vary significantly — and treating the wrong problem wastes months of effort. {{siteName}}'s sleep guides cover insomnia, sleep apnea, restless legs, and circadian rhythm disorders with symptom breakdowns, self-assessment tools, and treatment options from CBT-I (the most effective non-drug insomnia treatment) to when a sleep study is warranted. We explain why sleep hygiene alone is often insufficient and what actually moves the needle.` },
  },
  'credit-cards-banking': {
    'cash-back': { headline: 'Best Cash Back Credit Card Guides', intro: `Cash back cards are the simplest way to earn from everyday spending — but choosing between flat-rate, tiered, and rotating category structures requires understanding your actual spending patterns. {{siteName}}'s cash back card guides compare the highest-earning options for groceries, gas, dining, and general spending, with honest calculations of realistic annual earnings after fees. We include the specific card combinations that maximize returns across all spending categories for people who want to optimize without managing a complicated wallet.` },
    'travel-cards': { headline: 'Travel Rewards Credit Card Guides', intro: `Travel rewards cards can fund international flights and hotel stays — but only if you understand how the points systems work. {{siteName}}'s travel card guides explain transfer partners, point valuations, sign-up bonus strategies, and how to actually book award travel without paying cash. We compare the major travel cards by annual fee versus realistic value, identify which cards are worth the premium for frequent travelers, and explain the free night, lounge access, and travel insurance benefits that can offset high annual fees.` },
    'credit-score': { headline: 'Credit Score Improvement Guides', intro: `Your credit score determines the interest rate on every major purchase of your life — and most people have a meaningfully lower score than they could with a few targeted actions. {{siteName}}'s credit score guides explain exactly how FICO scores are calculated, the fastest legal ways to improve your score, how to dispute errors effectively, and the impact of specific actions like credit utilization changes, authorized user status, and secured cards. We include timelines so you know what to expect and when.` },
    'balance-transfer': { headline: 'Balance Transfer Card Guides', intro: `A balance transfer to a 0% APR card can save hundreds or thousands in interest on existing debt — but the details matter. {{siteName}}'s balance transfer guides explain how to calculate whether a transfer makes financial sense, what transfer fees actually cost you, what happens when the promotional period ends, and the common mistakes (continuing to spend on the card, missing minimum payments) that cost people their 0% rate. We include a current comparison of the best balance transfer offers and their key terms.` },
    'banking': { headline: 'Banking & Savings Account Guides', intro: `Online banks currently pay 4-5% APY on high-yield savings accounts while traditional banks pay under 0.5% — and the difference on a $10,000 emergency fund is $400 per year. {{siteName}}'s banking guides compare the best high-yield savings accounts, explain FDIC insurance limits, and help you understand which banking features actually matter versus which are just marketing. We also cover checking account options, overdraft policies, and how to structure accounts to automate your savings effectively.` },
    'credit-basics': { headline: 'Credit Basics Guides', intro: `Understanding how credit works gives you a permanent financial advantage. {{siteName}}'s credit basics guides cover the credit utilization ratio and its outsized impact on your score, the difference between hard and soft inquiries, how long negative items actually stay on your report, and what lenders look for beyond your FICO score. Whether you're building credit for the first time or recovering from past problems, our guides give you an accurate map of the credit system and the most effective path to the score you need.` },
  },
  'weight-loss-fitness': {
    'weight-loss': { headline: 'Weight Loss Guides', intro: `Weight loss is ultimately a function of calorie balance — but making that sustainable requires understanding why it's hard. {{siteName}}'s weight loss guides address the physiology, psychology, and practical strategy of fat loss: how much of a deficit actually works, why the scale stalls, how to protect muscle while losing fat, and which popular approaches have actual evidence behind them. We separate the genuinely effective strategies from the large category of things that work only in short-term studies or for people very different from you.` },
    'strength-training': { headline: 'Strength Training Guides', intro: `Strength training is the single most effective intervention for long-term body composition, metabolic health, and functional aging — and most people do it inefficiently. {{siteName}}'s strength training guides cover beginner program selection, progressive overload principles, the major compound movements, recovery requirements, and how to continue making progress after the first year. We write for people who want to get strong and stay injury-free, not for competitive powerlifters.` },
    'cardio': { headline: 'Cardio & HIIT Guides', intro: `Cardio's role in fitness is more specific and less central than most people assume — and doing it wrong wastes significant time. {{siteName}}'s cardio guides explain the difference between zone 2 training and HIIT, how much cardio is actually useful for fat loss, the cardiovascular health benefits that have real evidence behind them, and how to structure cardio around strength training without interfering with recovery. We include practical programming for beginners through experienced athletes.` },
    'nutrition': { headline: 'Fitness Nutrition Guides', intro: `Nutrition is where most fitness goals succeed or fail. {{siteName}}'s fitness nutrition guides cut through the noise on protein requirements, the actual evidence on meal timing, how to hit macros without obsessive tracking, and what to eat before and after training. We cover real food approaches, flexible dieting, and the specific challenges of eating well when busy — including meal prep strategies that actually work in a realistic schedule without requiring three hours on Sunday.` },
    'home-workouts': { headline: 'Home Workout Guides', intro: `A gym membership is optional. {{siteName}}'s home workout guides cover effective training with minimal equipment: bodyweight progressions, resistance bands, dumbbells, and kettlebells. We include complete programs for fat loss, muscle building, and general fitness that can be done in 30-45 minutes in a small space. Each program includes modifications for different fitness levels and guidance on progressive overload so you can keep improving without buying new equipment every few months.` },
    'motivation': { headline: 'Fitness Motivation & Habit Guides', intro: `Motivation gets you started. Systems keep you going. {{siteName}}'s fitness habit guides address the psychological and behavioral side of staying consistent: why people quit, how to design a routine you'll actually maintain, how to recover from missed weeks without abandoning the whole effort, and what the research on habit formation actually says about building exercise into your life permanently. We focus on sustainable behavior change rather than the high-intensity, unsustainable approach that dominates fitness marketing.` },
  },
  'automotive-guide': {
    'car-buying': { headline: 'Car Buying Guides', intro: `Buying a car is one of the largest financial decisions most people make — and dealerships are specifically trained to maximize what you pay. {{siteName}}'s car buying guides cover how to research and compare vehicles, negotiate the out-the-door price (not the monthly payment), evaluate financing versus paying cash, and identify the fees that are legitimate versus the ones you should refuse. We include specific scripts for common dealer tactics and the steps that save the average buyer $1,500-$3,000 on a new or used vehicle.` },
    'maintenance': { headline: 'Car Maintenance Guides', intro: `Following your car's actual maintenance schedule — not the service center's upsell schedule — is the difference between responsible ownership and expensive over-servicing. {{siteName}}'s car maintenance guides cover what every service actually does, which intervals are manufacturer-recommended versus dealer-recommended, and how to evaluate whether you need a service now or can safely wait. We include model-specific guidance for the most common vehicles and help you understand which maintenance tasks you can do yourself versus which require a shop.` },
    'repairs': { headline: 'Car Repair Cost Guides', intro: `Car repair costs vary enormously by make, model, shop, and region — and knowing what a repair should cost before you get a quote is the single best protection against being overcharged. {{siteName}}'s car repair guides cover the most common repairs by cost range, what labor rates look like nationally versus by region, how to evaluate a shop estimate, and which repairs are safe to delay versus which need immediate attention. We include the actual parts and labor breakdown most shops won't show you unprompted.` },
    'car-insurance': { headline: 'Car Insurance Optimization Guides', intro: `Most drivers are either underinsured or significantly overpaying for car insurance. {{siteName}}'s car insurance guides help you understand what coverage you actually need based on your vehicle value and financial situation, which discounts to ask for specifically, and how often to shop your policy to maintain competitive rates. We explain how claims affect your premium, when to use insurance versus pay out of pocket, and the often-misunderstood gap coverage that protects financed vehicle owners.` },
    'electric-vehicles': { headline: 'Electric Vehicle Guides', intro: `The EV decision involves more variables than a traditional car purchase — charging infrastructure, range anxiety, total cost of ownership, and rapidly changing incentive programs. {{siteName}}'s electric vehicle guides help you evaluate whether an EV makes sense for your specific driving patterns, compare the real cost of ownership against comparable gas vehicles, understand home charging setup costs, and navigate the federal and state tax credit eligibility rules that can significantly reduce your purchase price.` },
    'tires-wheels': { headline: 'Tire & Wheel Guides', intro: `Tires are the most safety-critical component on your car and the one most frequently bought on insufficient information. {{siteName}}'s tire guides cover how to read and understand tire specifications, what all-season versus summer versus winter tires actually deliver, how to compare tire brands and lines by real-world performance data, and when rotation, balancing, and alignment are genuinely needed. We include cost guides for the most popular tire sizes so you can evaluate quotes with confidence.` },
  },
  'online-education': {
    'coding': { headline: 'Coding & Programming Course Guides', intro: `Learning to code has never been more accessible — or more confusing to navigate, given thousands of courses, bootcamps, and self-taught resources competing for your attention. {{siteName}}'s coding guides help you choose the right learning path for your goals: career changers, professionals adding technical skills, and hobbyists all need very different things. We compare bootcamps, online courses, and free resources with honest assessments of job placement rates, time commitment, and which languages and frameworks are worth learning first.` },
    'certifications': { headline: 'Professional Certification Guides', intro: `The right certification can add meaningful salary leverage and career mobility — but many certifications are expensive, time-consuming, and not valued by the employers you're targeting. {{siteName}}'s certification guides identify which credentials have genuine market value in IT, project management, data, and marketing, how long preparation realistically takes, what study resources produce the best pass rates, and which certifications have strong ROI versus which are primarily resume decoration.` },
    'college-degrees': { headline: 'Online Degree Guides', intro: `Online degrees from accredited universities have achieved near-parity with in-person credentials at many employers — but the accreditation status, employer perception, and cost vary enormously. {{siteName}}'s online degree guides help you evaluate programs by accreditation type, compare tuition costs and financial aid availability, understand the time commitment of asynchronous versus synchronous programs, and identify the degree fields where online credentials have the most and least acceptance with specific employer categories.` },
    'skills-courses': { headline: 'Online Skills Course Guides', intro: `Platforms like Coursera, Udemy, LinkedIn Learning, and Skillshare each have different content strengths, instructor quality standards, and completion structures. {{siteName}}'s online course guides help you find high-quality learning in specific skill areas, identify which platform has the best content for your goal, understand the difference between courses that produce real skill versus ones that just feel productive, and get the most from self-paced learning if you struggle with completion.` },
    'career-development': { headline: 'Career Development Guides', intro: `Career advancement rarely happens by accident — it requires deliberate skill development, strategic visibility, and the ability to demonstrate value clearly. {{siteName}}'s career development guides cover salary negotiation, promotion positioning, professional networking that actually works, how to build a personal brand in your field, and how to navigate a career change with minimal financial risk. We focus on the actions with the highest leverage-to-effort ratio for people with demanding jobs and limited time.` },
    'free-learning': { headline: 'Free Online Learning Guides', intro: `Quality education is available for free from MIT, Harvard, and hundreds of other institutions — and knowing where to find it separates people who use the internet as a learning tool from those who just watch YouTube. {{siteName}}'s free learning guides cover the best free course platforms, open courseware, YouTube channels with genuine educational depth, and strategies for self-directed learning that produces real competence. We help you build a structured curriculum from free resources so you're not just collecting courses without finishing them.` },
  },
  'cybersecurity-privacy': {
    'password-security': { headline: 'Password Security Guides', intro: `Weak or reused passwords are the most common entry point for account takeovers — and a password manager eliminates this risk almost entirely for $3/month. {{siteName}}'s password security guides compare the best managers by security architecture, ease of use, and cross-device performance, explain how to migrate from browser-saved passwords safely, and walk you through enabling two-factor authentication on your most important accounts. We include the settings most people miss that significantly improve their security posture.` },
    'phishing': { headline: 'Phishing & Scam Defense Guides', intro: `Modern phishing attacks are sophisticated enough to fool technical users — and understanding the current tactics is the best defense. {{siteName}}'s phishing guides cover email, SMS, and voice phishing methods with specific examples of what convincing attacks look like today, the red flags that reliably identify them, and what to do if you've already clicked. We address business email compromise, QR code phishing, and the increasingly targeted attacks that go after specific individuals rather than mass audiences.` },
    'vpn-privacy': { headline: 'VPN & Online Privacy Guides', intro: `VPNs are widely recommended and widely misunderstood. {{siteName}}'s VPN guides explain what a VPN actually protects against (and what it doesn't), how to evaluate no-log claims with skepticism, which VPN providers have the best combination of privacy practices and performance, and when a VPN genuinely improves your security versus when it's unnecessary. We also cover browser fingerprinting, tracker blocking, and the practical privacy measures that make a measurable difference in reducing your data exposure.` },
    'device-security': { headline: 'Device Security Guides', intro: `Your devices are only as secure as their weakest setting — and default configurations often prioritize convenience over security. {{siteName}}'s device security guides cover antivirus and anti-malware for Windows and Mac, Android and iOS security settings worth changing, how ransomware works and how to protect against it, and the backup strategy that means a ransomware attack is inconvenient rather than catastrophic. We focus on practical, maintainable security that real people will actually implement.` },
    'wifi-network': { headline: 'Home Network Security Guides', intro: `Your home router is often the least-secured device on your network and the one most targeted by attackers. {{siteName}}'s network security guides cover the specific router settings that matter for home security, how to segment IoT devices from your primary network, what WPA3 encryption means practically, and how to identify unauthorized devices on your network. We write for people who aren't network engineers — practical steps that improve security without requiring a degree in networking.` },
    'identity-theft': { headline: 'Identity Theft Protection Guides', intro: `Identity theft affects 15 million Americans annually — and recovery averages over 200 hours and years of credit impact. {{siteName}}'s identity theft guides cover how to place a credit freeze (the single most effective protection), how to monitor for your personal data in breaches, what to do in the first 48 hours after discovering your identity has been compromised, and how to evaluate identity theft protection services honestly. We separate the services worth paying for from the ones that just alert you after damage is done.` },
  },
  'mental-health-wellness': {
    'anxiety': { headline: 'Anxiety Guides', intro: `Anxiety is the most common mental health condition in the US — and it's also one of the most treatable, with specific approaches showing strong results in randomized trials. {{siteName}}'s anxiety guides explain the difference between GAD, social anxiety, panic disorder, and situational anxiety, what the research says about CBT, medication, and lifestyle interventions, and how to find appropriate professional help if self-help approaches aren't enough. We write for people navigating anxiety in real life, not just in therapeutic settings.` },
    'depression': { headline: 'Depression Guides', intro: `Depression is a medical condition, not a character flaw — and the right information can make the difference between years of unnecessary suffering and effective treatment. {{siteName}}'s depression guides explain how clinical depression differs from normal sadness, what treatment options exist and how they compare, how to support someone with depression without burning out, and what to do when first-line treatments don't work. We cover the overlap between depression, anxiety, burnout, and grief that complicates many people's experiences.` },
    'sleep-wellness': { headline: 'Sleep Improvement Guides', intro: `Sleep is the foundation of mental and physical health — and it's the most commonly sacrificed resource in modern life. {{siteName}}'s sleep guides cover the evidence-based approaches to improving sleep quality, including sleep hygiene, CBT-I protocols, and the specific interventions that work better than the advice most people have already tried. We cover the sleep challenges specific to anxiety, depression, shift work, perimenopause, and aging, so you can find guidance relevant to your actual situation.` },
    'stress': { headline: 'Stress Management Guides', intro: `Chronic stress is a physiological state with measurable health consequences — and managing it requires more than being told to relax. {{siteName}}'s stress management guides cover the nervous system biology behind stress responses, evidence-based interventions that actually lower cortisol, how to identify and address the sources of stress rather than just managing symptoms, and the role of sleep, exercise, and social connection in building stress resilience. We distinguish between strategies that work in the moment and those that change your baseline over time.` },
    'therapy': { headline: 'Therapy & Mental Health Treatment Guides', intro: `Finding effective mental health treatment means navigating a confusing landscape of therapist types, therapy modalities, and practical access barriers. {{siteName}}'s therapy guides explain the difference between psychologists, therapists, counselors, and psychiatrists, what CBT, DBT, EMDR, and other approaches actually involve, how to find and evaluate a therapist, and what to do when therapy isn't working. We address insurance coverage, cost, telehealth options, and how to get help when access is the barrier.` },
    'self-care': { headline: 'Self-Care & Mindfulness Guides', intro: `Self-care is not bubble baths and scented candles — it's the set of practices that maintain your capacity to function well. {{siteName}}'s self-care guides cover mindfulness and meditation with an emphasis on the research-backed approaches, journaling methods that produce actual psychological benefit, boundary-setting as a practical skill, and the daily habits that have the strongest evidence for sustained wellbeing. We focus on accessible practices that work for people with demanding lives and limited time.` },
  },
  'home-security-systems': {
    'cameras': { headline: 'Home Security Camera Guides', intro: `Security cameras have become one of the most accessible home security investments — but the range of quality, privacy practices, and subscription requirements varies enormously. {{siteName}}'s camera guides compare indoor, outdoor, and doorbell cameras on resolution, night vision, storage options, local versus cloud recording, and the privacy policies of major brands. We include setup guides for the most popular systems and honest assessments of which features actually matter for crime deterrence versus which are marketing.` },
    'alarm-systems': { headline: 'Home Alarm System Guides', intro: `A monitored alarm system is one of the most effective crime deterrents available — but the contract terms, monitoring fees, and equipment costs vary significantly. {{siteName}}'s alarm system guides compare professional monitoring providers on monthly cost, response times, contract flexibility, and equipment quality. We cover the differences between hardwired and wireless systems, what cellular backup means for reliability, and how to evaluate the total cost of ownership beyond the advertised monthly rate.` },
    'smart-locks': { headline: 'Smart Lock Guides', intro: `Smart locks add keypad access, remote locking, and access logs to your front door — and the best ones integrate with your existing deadbolt and home automation system. {{siteName}}'s smart lock guides compare the leading options on security certifications (ANSI/BHMA grade), battery life, integration with Alexa, Google, and Apple platforms, and installation difficulty. We cover the specific use cases where smart locks provide real value: rentals, family members who lose keys, and remote access management.` },
    'diy-security': { headline: 'DIY Home Security Guides', intro: `Professional installation is optional — and avoiding it can save you several hundred dollars and a long-term contract. {{siteName}}'s DIY security guides cover self-installed systems that don't require a technician, self-monitoring options that work without monthly fees, and how to combine individual devices (cameras, sensors, smart locks) into a cohesive system. We include the specific tools needed for installation, the common mistakes that lead to false alarms, and how DIY systems compare to professionally installed alternatives.` },
    'professional-monitoring': { headline: 'Professional Security Monitoring Guides', intro: `Professional monitoring means trained operators respond to alerts and contact emergency services if you're unavailable or unable to respond. {{siteName}}'s monitoring service guides compare the major providers on response time (a significant differentiator), monitoring center locations, contract terms and cancellation policies, and compatibility with your existing equipment. We explain cellular versus broadband monitoring, what happens during a power outage, and how to evaluate monitoring claims that are difficult to verify independently.` },
    'video-doorbells': { headline: 'Video Doorbell Guides', intro: `Video doorbells have become the entry point for home security for millions of households — but the choice between Ring, Nest, Arlo, and others involves real tradeoffs in price, privacy, and capability. {{siteName}}'s video doorbell guides compare models on video quality, field of view, two-way audio, package detection, night vision performance, and subscription requirements for recorded video. We include installation guides for both wired and battery-powered options and cover the neighbor notification features that affect community dynamics.` },
  },
  'solar-energy': {
    'solar-panels': { headline: 'Solar Panel Guides', intro: `Solar panel technology has improved dramatically while costs have dropped 90% over the past decade — but choosing the right panels for your roof and location still requires understanding the basics. {{siteName}}'s solar panel guides cover monocrystalline versus polycrystalline technology, efficiency ratings and what they mean in practice, how to evaluate panel warranties, and what system size you actually need based on your electricity consumption. We help you have an informed conversation with installers rather than relying solely on their recommendations.` },
    'costs-savings': { headline: 'Solar Cost & Savings Guides', intro: `The solar financial decision comes down to payback period, financing cost, and electricity rate trajectory — and {{siteName}} covers all three with real numbers. Our solar cost guides break down the average installed system cost by system size and region, calculate realistic annual savings based on your utility rate, and explain the factors that most affect whether solar makes strong financial sense for your specific situation. We include the honest cases where solar doesn't pencil out and what changes that calculation.` },
    'battery-storage': { headline: 'Solar Battery Storage Guides', intro: `Home battery storage has moved from luxury to practical consideration as grid reliability declines and time-of-use rates spread. {{siteName}}'s battery storage guides cover the Tesla Powerwall, Enphase IQ, Franklin WH, and other leading options with honest capacity comparisons, cycling warranties, and real-world backup capabilities. We explain the difference between backup and self-consumption use cases, how batteries interact with net metering policies, and whether adding storage to an existing solar system makes financial sense.` },
    'installation': { headline: 'Solar Installation Guides', intro: `Solar installation quality varies more than most homeowners realize — and a poor installation affects system performance and roof integrity for decades. {{siteName}}'s installation guides cover how to evaluate installer credentials and workmanship warranties, what permits and inspections are required in most states, how to understand a proposal's technical specifications, and what the installation process actually looks like from contract to interconnection. We include red flags in installer proposals and the questions that separate quality installers from bottom-of-market operations.` },
    'incentives': { headline: 'Solar Incentives & Tax Credit Guides', intro: `The federal solar investment tax credit (ITC) and state-level incentives can reduce the net cost of a solar system by 30-50% — but the rules have specific requirements and limitations that affect eligibility. {{siteName}}'s incentive guides explain the current federal ITC percentage, how to claim it correctly, which state programs offer meaningful additional incentives, net metering policies by state, and the SRECs and utility programs that create ongoing income from excess production. We update these guides as incentive programs change.` },
    'solar-companies': { headline: 'Solar Company Reviews & Comparisons', intro: `The solar industry includes excellent installers and aggressive salespeople, and knowing the difference before signing a 20-25 year agreement is essential. {{siteName}}'s solar company guides evaluate national installers like Sunrun, SunPower, and Palmetto alongside the case for using local installers. We cover what to look for in reviews, how to verify contractor licensing, what a fair proposal looks like, and the contract terms that protect homeowners versus those that heavily favor the installer.` },
  },
  'senior-care-medicare': {
    'medicare': { headline: 'Medicare Guides', intro: `Medicare has four parts and dozens of plan options — and making the wrong enrollment decision can cost thousands annually or create coverage gaps that are difficult to reverse. {{siteName}}'s Medicare guides explain Parts A, B, C, and D in plain English, the critical enrollment windows and late-penalty rules, how to compare Medicare Advantage versus Original Medicare with a supplement, and how to evaluate Part D drug plans based on your specific medications. We cover the decisions that most affect senior healthcare costs and access.` },
    'assisted-living': { headline: 'Assisted Living Guides', intro: `Assisted living communities provide housing, personal care, and social activities for seniors who need some support but not intensive medical care — and the cost and quality range is enormous. {{siteName}}'s assisted living guides cover average costs by state, what's typically included in base rates versus charged as extras, how to evaluate a facility's inspection records and staff turnover, and the key questions to ask during tours. We also cover memory care units for dementia patients, which have different staffing and programming requirements than standard assisted living.` },
    'in-home-care': { headline: 'In-Home Senior Care Guides', intro: `Most seniors prefer to age at home — and home care makes that possible for longer than most families realize. {{siteName}}'s in-home care guides explain the difference between companion care, personal care aides, and home health aides (a distinction that affects both cost and insurance coverage), how to find and vet caregivers whether through an agency or independently, what home modifications improve safety and independence, and how to coordinate care across multiple providers and family members.` },
    'costs': { headline: 'Senior Care Cost Guides', intro: `Senior care is one of the most significant financial planning challenges families face — and the costs are higher than most people estimate until they need care. {{siteName}}'s senior care cost guides cover the real costs of in-home care, assisted living, memory care, and skilled nursing facilities by state, how Medicare, Medicaid, and long-term care insurance each cover (or don't cover) different care types, and the financial planning strategies that protect assets while qualifying for public benefits.` },
    'dementia-care': { headline: 'Dementia & Alzheimer\'s Care Guides', intro: `Caring for someone with dementia requires specific knowledge that most families have to acquire under enormous stress. {{siteName}}'s dementia care guides cover the progression of Alzheimer's and other dementias, the communication strategies that reduce agitation and improve daily interactions, home safety modifications for different stages, when in-home care is no longer sustainable, and how to evaluate memory care facilities specifically. We address both the practical and emotional aspects of caregiving, including caregiver burnout.` },
    'retirement-planning': { headline: 'Retirement Planning Guides for Seniors', intro: `Retirement planning in your 60s and beyond focuses on different questions than accumulation-phase planning: withdrawal sequencing, Social Security timing, RMD management, and long-term care funding. {{siteName}}'s senior retirement planning guides cover the Social Security claiming decision and its lifetime dollar impact, how to structure withdrawals to minimize lifetime tax, when a Roth conversion makes sense in retirement, and how to plan for a long retirement while protecting against outliving your assets.` },
  },
  'business-startup': {
    'business-ideas': { headline: 'Business Idea Guides', intro: `The best business idea for you is one where your skills and knowledge intersect with a genuine market need — and finding that intersection requires more than browsing lists of trending businesses. {{siteName}}'s business idea guides help you evaluate opportunities against your specific resources, identify underserved niches in your local market, and assess whether a business model is viable before investing significant time or money. We cover service businesses, digital products, and physical products with honest assessments of startup costs and realistic timelines to profitability.` },
    'legal-setup': { headline: 'Business Legal Setup Guides', intro: `Getting your business structure right from the start protects your personal assets and simplifies taxes — and the right structure depends on your business type and risk profile. {{siteName}}'s legal setup guides explain the practical differences between sole proprietorships, LLCs, and S corporations, when you need a registered agent, how to apply for an EIN, and what operating agreements and business bank accounts actually do for you legally. We focus on the decisions that matter most for small and micro-businesses rather than enterprise-level concerns.` },
    'funding': { headline: 'Business Funding Guides', intro: `Most small businesses are funded by their founders — and understanding what funding options actually exist, and which are appropriate for your stage and business type, prevents costly mistakes. {{siteName}}'s business funding guides cover bootstrapping strategies, SBA loans and their real requirements, SBIR grants for eligible businesses, angel investment, and the revenue-based financing and business credit options that work when traditional bank loans don't. We address the funding gap most small business owners face: too small for venture capital, too new for bank loans.` },
    'marketing': { headline: 'Small Business Marketing Guides', intro: `Marketing a small business efficiently means focusing on the channels that reliably produce customers for your specific type of business — not trying everything at once. {{siteName}}'s small business marketing guides cover local SEO for service businesses, Google Business Profile optimization, content marketing for expertise-based businesses, email list building, and paid advertising with small budgets. We focus on what actually works at sub-$1,000/month marketing budgets, where most small businesses operate.` },
    'operations': { headline: 'Business Operations Guides', intro: `Operational efficiency is where small business profits are made or lost. {{siteName}}'s operations guides cover the tools and systems that eliminate manual work, improve consistency, and make it possible to grow without hiring proportionally. We cover project management tools, CRM systems for small teams, accounting software, automation for repetitive tasks, and how to document processes so your business doesn't depend on you personally handling everything. We focus on practical implementations for businesses with 1-10 employees.` },
    'freelancing': { headline: 'Freelancing & Consulting Guides', intro: `Freelancing offers income flexibility and independence — but building a sustainable freelance business requires more than skill in your chosen field. {{siteName}}'s freelancing guides cover finding first clients through methods that work without an existing network, setting rates that reflect your value and market position, writing proposals that convert, managing contracts and late-paying clients, and transitioning from project work to retainer relationships that provide predictable income. We address the specific challenges of the first year of freelancing when income is unpredictable.` },
  },

};

/**
 * Get intro for a specific niche + category.
 * Returns null if not found (caller falls back to generic).
 */
export function getCategoryIntro(nicheSlug, categorySlug) {
  return INTROS[nicheSlug]?.[categorySlug] || null;
}

/**
 * All intros for a niche — used during spawn to pre-generate all category pages.
 */
export function getAllCategoryIntros(nicheSlug) {
  return INTROS[nicheSlug] || {};
}
